name : 'NodeCI'

on:
  push: 
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build: 
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports: 
          - 6379:6379

    env:
      port: 3000
      NODE_ENV: CI
      MONGODB_URI: ${{ secrets.MONGODB_URI }}

    steps:
      - name: checkout repo
        uses: actions/checkout@v3

      - name: setup node env
        uses: actions/setup-node@v3
        with:
          node-version: "18.20.4"
          cache: "npm"

      - name: Install dependencies
        run: |
          npm install

      - name: start server
        run: |
          nohup npm run start & 
          sleep 5 
          
      - name: Run test  
        run: |
          npm run test  

      - name: stop server
        run: |
          pkill -f node    

